// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJH6W014IIlb3oQWvhRyjzCdqzHJh1-o',
    appId: '1:154668288998:web:04dcfd735cbc0f7069e427',
    messagingSenderId: '154668288998',
    projectId: 'flutter-noel',
    authDomain: 'flutter-noel.firebaseapp.com',
    storageBucket: 'flutter-noel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2LiNLW2hd-p6vQWuaO1z6vrTsEvufXE',
    appId: '1:154668288998:android:9628b0a7e1b6b4cb69e427',
    messagingSenderId: '154668288998',
    projectId: 'flutter-noel',
    storageBucket: 'flutter-noel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEQ2aLzsuchESfCK3NstDhkq-ctPUQaQ4',
    appId: '1:154668288998:ios:cbba1fea3e93a88a69e427',
    messagingSenderId: '154668288998',
    projectId: 'flutter-noel',
    storageBucket: 'flutter-noel.appspot.com',
    androidClientId: '154668288998-8flrfivvtrbaonvub8et6qfi1tmvl37n.apps.googleusercontent.com',
    iosClientId: '154668288998-n7k0cmcgpc7v00q9qi0cljm7sigg2s2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEQ2aLzsuchESfCK3NstDhkq-ctPUQaQ4',
    appId: '1:154668288998:ios:cbba1fea3e93a88a69e427',
    messagingSenderId: '154668288998',
    projectId: 'flutter-noel',
    storageBucket: 'flutter-noel.appspot.com',
    androidClientId: '154668288998-8flrfivvtrbaonvub8et6qfi1tmvl37n.apps.googleusercontent.com',
    iosClientId: '154668288998-n7k0cmcgpc7v00q9qi0cljm7sigg2s2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoel',
  );
}
